# Generated by Django 5.2.4 on 2025-07-29 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking_table',
            new_name='Booking',
        ),
        migrations.RenameModel(
            old_name='Menu_table',
            new_name='Menu',
        ),
    ]
